apiVersion: v1
kind: Service
metadata:
  name: monitor-api-service
  namespace: monitoring
  labels:
    app: monitor-api
spec:
  type: LoadBalancer
  selector:
    app: monitor-api
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: monitor-runner-service
  namespace: monitoring
  labels:
    app: monitor-runner
spec:
  type: ClusterIP
  selector:
    app: monitor-runner
  ports:
  - name: http
    protocol: TCP
    port: 8081
    targetPort: 8081
